packages:
  - "web"
  - "signaling"
  - "e2e"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  '@parcel/watcher': true
  '@swc/core': true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - esbuild
  - '@parcel/watcher'
  - '@swc/core'
