// Mots à dessiner — concrets et rapides à esquisser (pas de concepts
// abstraits), voir hooks/use-duel-session.ts. Pas de i18n via next-intl ici :
// ce ne sont pas des libellés d'UI mais le contenu même du jeu, tiré par le
// dessinateur·rice selon la locale courante (voir pick-word.ts).

export const DUEL_WORDS_FR: readonly string[] = [
  "chat",
  "parapluie",
  "pizza",
  "fusée",
  "cactus",
  "sirène",
  "dinosaure",
  "château",
  "pirate",
  "glace",
  "vélo",
  "montagne",
  "robot",
  "poisson",
  "sorcière",
  "arc-en-ciel",
  "pieuvre",
  "guitare",
  "fantôme",
  "escargot",
  "avion",
  "pomme",
  "lune",
  "abeille",
  "tortue",
  "cœur",
  "licorne",
  "chapeau",
  "araignée",
  "flamant",
  "hibou",
  "trampoline",
  "baleine",
  "champignon",
];

export const DUEL_WORDS_EN: readonly string[] = [
  "cat",
  "umbrella",
  "pizza",
  "rocket",
  "cactus",
  "mermaid",
  "dinosaur",
  "castle",
  "pirate",
  "ice cream",
  "bicycle",
  "mountain",
  "robot",
  "fish",
  "witch",
  "rainbow",
  "octopus",
  "guitar",
  "ghost",
  "snail",
  "airplane",
  "apple",
  "moon",
  "bee",
  "turtle",
  "heart",
  "unicorn",
  "hat",
  "spider",
  "flamingo",
  "owl",
  "trampoline",
  "whale",
  "mushroom",
];
